[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["puppeteer", "puppeteer-core"]
  
[functions.generate-pdf]
  memory = 1024
  timeout = 30
  included_files = [
    "node_modules/mdpdf/**/*",
    "node_modules/puppeteer/**/*",
    "node_modules/puppeteer-core/**/*"
  ]
  [functions.generate-pdf.environment]
    TMPDIR = "/tmp"
    TEMP = "/tmp"
    TMP = "/tmp"
    URL = "https://amotivv-tools-mdpdf.netlify.app"
